-- TABLE FOR INCREMENTAL LOAD INFOMRATION
CREATE TABLE IF NOT EXISTS BL_CL.MTA_INCREMENTAL_LOAD (
	source_table_name VARCHAR NOT NULL,
	target_table_name VARCHAR NOT NULL,
	procedure_name VARCHAR NOT NULL,
	latest_load_ts TIMESTAMP NOT NULL
);