-- TABLE FOR LOG INFORMATION ABOUT LOADS
CREATE TABLE IF NOT EXISTS BL_CL.mta_logs (
	log_id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	log_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	procedure_name VARCHAR(255),
	n_records BIGINT,
	log_message TEXT DEFAULT 'SUCCESFUL LOAD'
);