-- GENERATE SEQUENCE FOR PK OF T MAP PROVINCES
CREATE SEQUENCE IF NOT EXISTS BL_CL.T_MAP_PROVINCES_ID_SEQ START 1;

-- CREATE TABLE FOR DEDUPLICATION OF PROVINCES
CREATE TABLE IF NOT EXISTS BL_CL.T_MAP_PROVINCES (
	province_id BIGINT NOT NULL DEFAULT nextval('BL_CL.T_MAP_PROVINCES_ID_SEQ'),
	province_name VARCHAR(255) NOT NULL,
	province_src_name VARCHAR(255),
	province_src_id VARCHAR(255),
	source_system VARCHAR(255),
	source_entity VARCHAR(255)
);

-- CONNECT SEQUENCE WITH PK OF T MAP PROVINCES
ALTER SEQUENCE BL_CL.T_MAP_PROVINCES_ID_SEQ OWNED BY BL_CL.T_MAP_PROVINCES.PROVINCE_ID;
