-- MASTER PROCEDURE TO LOAD DATA TO BL_DM LAYER
CREATE OR REPLACE PROCEDURE BL_CL.BL_DM_LOAD_MASTER()
LANGUAGE plpgsql
AS $$
BEGIN
	RAISE INFO 'LOADING DIM_DELIVERIES';
	CALL BL_CL.DIM_DELIVERIES_LOAD();
	COMMIT;
	RAISE INFO 'LOADING DIM_PRODUCTS';
	CALL BL_CL.DIM_PRODUCTS_LOAD();
	COMMIT;
	RAISE INFO 'LOADING DIM_CUSTOMERS';
	CALL BL_CL.DIM_CUSTOMERS_LOAD();
	COMMIT;
	RAISE INFO 'LOADING DIM_EMPLOYEES_SCD';
	CALL BL_CL.DIM_EMPLOYEES_SCD_LOAD();
	COMMIT;
	RAISE INFO 'LOADING DIM_PAYMENTS';
	CALL BL_CL.DIM_PAYMENTS_LOAD();
	COMMIT;
	RAISE INFO 'LOADING DIM_STORES';
	CALL BL_CL.DIM_STORES_LOAD();
	COMMIT;
	RAISE INFO 'LOADING FCT_SALES_DD';
	CALL BL_CL.FCT_SAlES_DD_LOAD();
	COMMIT;
	RAISE INFO 'FINISHED LOADING OF DM LAYER';
	COMMIT;
END;
$$;