-- CREATE DATABASE supermarket; -- ONLY FOR INITIALIZATION OF DATABASE
----------------------------

-- SQL SCRIPT FOR CREATING ALL SCHEMAS IN SUPERMARKET DATABASE
CREATE SCHEMA IF NOT EXISTS SA_SALES_ONLINE;
CREATE SCHEMA IF NOT EXISTS SA_SALES_OFFLINE;
CREATE SCHEMA IF NOT EXISTS BL_CL;
CREATE SCHEMA IF NOT EXISTS BL_3NF;
CREATE SCHEMA IF NOT EXISTS BL_DM;

-- CREATE EXTENSION FOR EXTENRAL TABLE LOADING AND CREATE A SERVER TO CONNECT TO SOURCES
CREATE EXTENSION IF NOT EXISTS file_fdw SCHEMA BL_CL;
CREATE SERVER IF NOT EXISTS file_server FOREIGN DATA WRAPPER file_fdw;