-- MASTER PROCEDURE TO LOAD DATA TO T MAP TABLES FOR DEDUPLICATION
CREATE OR REPLACE PROCEDURE BL_CL.DEDUPLICATION_LOAD_MASTER()
LANGUAGE plpgsql
AS $$
BEGIN
	RAISE INFO 'LOADING T_MAP_PROVINCES';
	CALL BL_CL.PROVINCES_DEDUPLICATION();
	COMMIT;
	RAISE INFO 'LOADING T_MAP_TOWNS';
	CALL BL_CL.TOWNS_DEDUPLICATION();
	COMMIT;
	RAISE INFO 'LOADING T_MAP_DISTRICTS';
	CALL BL_CL.DISTRICTS_DEDUPLICATION();
	COMMIT;
END;
$$