-- CREATE ROLE cl_user to store all privliges needed to load data
CREATE ROLE cl_user;

-- GRANT USAGE ON ALL SCHEMAS
GRANT CREATE, USAGE ON SCHEMA BL_CL, BL_3NF, BL_DM, SA_SALES_ONLINE, SA_SALES_OFFLINE TO cl_user;

-- GRANT FOLLOWING PRIVLIGES ON ALL SCHEMAS
GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA BL_CL, BL_3NF, BL_DM, SA_SALES_ONLINE, SA_SALES_OFFLINE TO cl_user;

-- GRANT USAGE ON FDW
GRANT USAGE ON FOREIGN DATA WRAPPER file_fdw TO cl_user;

-- OWNER OF EXTERNAL TABLES
ALTER TABLE sa_sales_offline.ext_sales_offline OWNER TO cl_user;
ALTER TABLE sa_sales_online.ext_sales_online OWNER TO cl_user;

-- GRANT EXECUTE OF ALL PROCEDURES AND FUNCTIONS
GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA BL_CL TO cl_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA BL_CL TO cl_user;

-- CREATE USER WHICH WILL LOAD THE DATA
CREATE ROLE dwh_user LOGIN PASSWORD 'password';
GRANT CONNECT ON DATABASE supermarket TO dwh_user;
GRANT cl_user TO dwh_user;