-- MASTER PROCEDURE TO LOAD DATA TO DATA WAREHOUSE. TWO PARAMETERS CAN BE GIVEN:
-- on_source = ABSOLUTE PATH TO ONLINE SOURCE
-- off_source = ABSOLUTE PATH TO OFFLINE SOURCES
-- DEFAULT PATHS GIVEN IN PROCEDURE 
CREATE OR REPLACE PROCEDURE BL_CL.DWH_LOAD_MASTER(on_source TEXT DEFAULT 'C:\Users\pawel\OneDrive\EPAM FILES\Final-Project\DATA SOURCES\SALES_ONLINE.CSV', 
													off_source TEXT DEFAULT 'C:\Users\pawel\OneDrive\EPAM FILES\Final-Project\DATA SOURCES\SALES_OFFLINE.CSV',
													skip_src_load BOOL DEFAULT TRUE)
LANGUAGE plpgsql
AS $$
BEGIN
	RAISE INFO 'START OF THE PROCEDURE. CREATING AND LOADING DATA FROM SOURCES, %', CURRENT_TIMESTAMP;
	IF NOT skip_src_load THEN
		
		RAISE INFO 'LOADING DATA TO SA_SALES_ONLINE FROM ONLINE SOURCE, %', CURRENT_TIMESTAMP;
		CALL BL_CL.SRC_ONLINE_SALES_LOAD_CSV(on_source);
		COMMIT;
	
	END IF;
	
	IF NOT skip_src_load THEN
		RAISE INFO 'LOADING DATA TO SA_SALES_OFFLINE FROM OFFLINE SOURCE, %', CURRENT_TIMESTAMP;
		CALL BL_CL.SRC_OFFLINE_SALES_LOAD_CSV(off_source);
		COMMIT;
	
	END IF;

	RAISE INFO 'LOADING DATA TO MAP TABLES FROM BOTH SOURCE, %', CURRENT_TIMESTAMP;
	CALL BL_CL.DEDUPLICATION_LOAD_MASTER();
	COMMIT;
	RAISE INFO 'BUILDING BL_3NF LAYER, %', CURRENT_TIMESTAMP;
	CALL BL_CL.BL_3NF_LOAD_MASTER();
	COMMIT;
	RAISE INFO 'BUILDING BL_DM LAYER, %', CURRENT_TIMESTAMP;
	CALL BL_CL.BL_DM_LOAD_MASTER();
	COMMIT;
	RAISE INFO 'BUILDING DWH COMPLETED';
END;
$$;