CREATE SCHEMA IF NOT EXISTS BL_3NF;

-- GENERATE SEQUENCE FOR PK OF CE_ADDRESSES
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_ADDRESS_ID START 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_ADDRESSES (
	address_id BIGINT PRIMARY KEY,
	address VARCHAR(255) NOT NULL,
	district_id BIGINT NOT NULL REFERENCES BL_3NF.CE_DISTRICTS (district_id),
	source_system VARCHAR(255) NOT NULL,
	source_entity VARCHAR(255) NOT NULL,
	address_src_id VARCHAR(255) NOT NULL,
	insert_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CONNECT SEQUENCE WITH PK OF CE_ADDRESSES
ALTER SEQUENCE BL_3NF.SEQ_CE_ADDRESS_ID OWNED BY BL_3NF.CE_ADDRESSES.ADDRESS_ID;

-- INSERT DEFAULT ROW
INSERT INTO BL_3NF.CE_ADDRESSES (address_id, address, district_id, address_src_id, source_system, source_entity, insert_dt, update_dt) 
SELECT -1 AS id,
			'n. a.',
			-1,
			'n. a.',
			'MANUAL',
			'MANUAL',
			'1990-01-01'::TIMESTAMP,
			'1990-01-01'::TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_ADDRESSES WHERE address_id = -1);

COMMIT;