CREATE SCHEMA IF NOT EXISTS BL_3NF;

-- GENERATE SEQUENCE FOR PK OF CE_DELIVERIES
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_DELIVERY_ID START 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_DELIVERIES (
	delivery_id BIGINT PRIMARY KEY,
	delivery_method_id BIGINT NOT NULL REFERENCES BL_3NF.CE_DELIVERY_METHODS (delivery_method_id),
	address_id BIGINT NOT NULL REFERENCES BL_3NF.CE_ADDRESSES (address_id),
	source_system VARCHAR(255) NOT NULL,
	source_entity VARCHAR(255) NOT NULL,
	delivery_src_id VARCHAR(255) NOT NULL,
	insert_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CONNECT SEQUENCE WITH PK OF CE_DELIVERIES
ALTER SEQUENCE BL_3NF.SEQ_CE_DELIVERY_ID OWNED BY BL_3NF.CE_DELIVERIES.DELIVERY_ID;

-- INSERT DEFAULT ROW
INSERT INTO BL_3NF.CE_DELIVERIES (delivery_id, delivery_method_id, address_id, delivery_src_id, source_system, source_entity, insert_dt, update_dt) 
SELECT -1 AS id,
		-1,
		-1,
		'n. a.',
		'MANUAL',
		'MANUAL',
		'1990-01-01'::TIMESTAMP,
		'1990-01-01'::TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_DELIVERIES WHERE delivery_id = -1);

COMMIT;