CREATE SCHEMA IF NOT EXISTS BL_3NF;

-- GENERATE SEQUENCE FOR PK OF CE_DELIVERY_METHODS
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_DELIVERY_METHOD_ID START 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_DELIVERY_METHODS (
	delivery_method_id BIGINT PRIMARY KEY,
	delivery_method_name VARCHAR(255) NOT NULL,
	source_system VARCHAR(255) NOT NULL,
	source_entity VARCHAR(255) NOT NULL,
	delivery_method_src_id VARCHAR(255) NOT NULL,
	insert_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CONNECT SEQUENCE WITH PK OF CE_DELIVERY_METHODS
ALTER SEQUENCE BL_3NF.SEQ_CE_DELIVERY_METHOD_ID OWNED BY BL_3NF.CE_DELIVERY_METHODS.DELIVERY_METHOD_ID;

-- INSERT DEFAULT ROW
INSERT INTO BL_3NF.CE_DELIVERY_METHODS (delivery_method_id, delivery_method_name, delivery_method_src_id, source_system, source_entity, insert_dt, update_dt) 
SELECT -1 AS id,
		'n. a.',
		'n. a.',
		'MANUAL',
		'MANUAL',
		'1990-01-01'::TIMESTAMP,
		'1990-01-01'::TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_DELIVERY_METHODS WHERE delivery_method_id = -1);

COMMIT;