CREATE SCHEMA IF NOT EXISTS BL_3NF;

-- GENERATE SEQUENCE FOR PK OF CE_EMPLOYEES_SCD
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_EMPLOYEE_ID START 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_EMPLOYEES_SCD (
	employee_id BIGINT,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	phone_number VARCHAR(255) NOT NULL,
	gender VARCHAR(255) NOT NULL,
	start_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	end_dt TIMESTAMP NOT NULL DEFAULT '9999-12-31'::TIMESTAMP,
	is_active BOOL DEFAULT TRUE,
	source_system VARCHAR(255) NOT NULL,
	source_entity VARCHAR(255) NOT NULL,
	employee_src_id VARCHAR(255) NOT NULL,
	insert_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (employee_id, start_dt)
);

-- CONNECT SEQUENCE WITH PK OF CE_EMPLOYEES_SCD
ALTER SEQUENCE BL_3NF.SEQ_CE_EMPLOYEE_ID OWNED BY BL_3NF.CE_EMPLOYEES_SCD.EMPLOYEE_ID;

-- INSERT DEFAULT ROW
INSERT INTO BL_3NF.CE_EMPLOYEES_SCD (employee_id, first_name, last_name, email, phone_number, gender, start_dt, end_dt, is_active, employee_src_id, source_system, source_entity, insert_dt, update_dt) 
SELECT -1 AS id,
		'n. a.',
		'n. a.',
		'n. a.',
		'n. a.',
		'n. a.',
		'1990-01-01'::TIMESTAMP,
		'9999-12-31'::TIMESTAMP,
		TRUE,
		'n. a.',
		'MANUAL',
		'MANUAL',
		'1990-01-01'::TIMESTAMP,
		'1990-01-01'::TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_EMPLOYEES_SCD WHERE employee_id = -1);

COMMIT;