CREATE SCHEMA IF NOT EXISTS BL_3NF;

-- GENERATE SEQUENCE FOR PK OF CE_PAYMENT_METHODS
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_PAYMENT_METHOD_ID START 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_PAYMENT_METHODS (
	payment_method_id BIGINT PRIMARY KEY,
	payment_name VARCHAR(255) NOT NULL,
	source_system VARCHAR(255) NOT NULL,
	source_entity VARCHAR(255) NOT NULL,
	payment_method_src_id VARCHAR(255) NOT NULL,
	insert_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CONNECT SEQUENCE WITH PK OF CE_PAYMENT_METHODS
ALTER SEQUENCE BL_3NF.SEQ_CE_PAYMENT_METHOD_ID OWNED BY BL_3NF.CE_PAYMENT_METHODS.PAYMENT_METHOD_ID;

-- INSERT DEFAULT ROW
INSERT INTO BL_3NF.CE_PAYMENT_METHODS (payment_method_id, payment_name, payment_method_src_id, source_system, source_entity, insert_dt, update_dt) 
SELECT -1 AS id,
		'n. a.',
		'n. a.',
		'MANUAL',
		'MANUAL',
		'1990-01-01'::TIMESTAMP,
		'1990-01-01'::TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PAYMENT_METHODS WHERE payment_method_id = -1);

COMMIT;