CREATE SCHEMA IF NOT EXISTS BL_3NF;

-- GENERATE SEQUENCE FOR PK OF CE_SALES
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_SALE_ID START 1;

-- CREATE CE_SALES TABLE
CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES (
	sale_id BIGINT PRIMARY KEY,
	order_id BIGINT NOT NULL,
	customer_id BIGINT NOT NULL, --REFERENCES BL_3NF.CE_CUSTOMERS (customer_id),
	payment_method_id BIGINT NOT NULL, --REFERENCES BL_3NF.CE_PAYMENT_METHODS (payment_method_id),
	delivery_id BIGINT NOT NULL, --REFERENCES BL_3NF.CE_DELIVERIES (delivery_id),
	store_id BIGINT NOT NULL, --REFERENCES BL_3NF.CE_STORES (store_id),
	product_id BIGINT NOT NULL, --REFERENCES BL_3NF.CE_PRODUCTS (product_id),
	employee_id BIGINT NOT NULL,
	event_dt DATE NOT NULL,
	delivery_fee NUMERIC(10,2),
	retail_price NUMERIC(10,2),
	quantity INT,
	sale_price NUMERIC(10, 2),
	source_system VARCHAR(255) NOT NULL,
	source_entity VARCHAR(255) NOT NULL,
	sale_src_id VARCHAR(255) NOT NULL,
	insert_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CONNECT SEQUENCE WITH PK OF CE_SALES
ALTER SEQUENCE BL_3NF.SEQ_CE_SALE_ID OWNED BY BL_3NF.CE_SALES.SALE_ID;
