CREATE SCHEMA IF NOT EXISTS BL_3NF;

-- GENERATE SEQUENCE FOR PK OF CE_STORES
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_STORE_ID START 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_STORES (
	store_id BIGINT PRIMARY KEY,
	address_id BIGINT NOT NULL REFERENCES BL_3NF.CE_ADDRESSES (address_id),
	store_name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	website VARCHAR(255) NOT NULL,
	source_system VARCHAR(255) NOT NULL,
	source_entity VARCHAR(255) NOT NULL,
	store_src_id VARCHAR(255) NOT NULL,
	insert_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_dt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CONNECT SEQUENCE WITH PK OF CE_STORES
ALTER SEQUENCE BL_3NF.SEQ_CE_STORE_ID OWNED BY BL_3NF.CE_STORES.STORE_ID;

-- INSERT DEFAULT ROW
INSERT INTO BL_3NF.CE_STORES (store_id, address_id, store_name, email, website, store_src_id, source_system, source_entity, insert_dt, update_dt) 
SELECT -1 AS id,
		-1,
		'n. a.',
		'n. a.',
		'n. a.',
		'n. a.',
		'MANUAL',
		'MANUAL',
		'1990-01-01'::TIMESTAMP,
		'1990-01-01'::TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STORES WHERE store_id = -1);

COMMIT;